
-- TOKEN_ADMIN - Min privileges to create a token
--GRANT CONNECT ON DATABASE TO ROLE TOKEN_ADMIN;
--GRANT SELECTIN ON SCHEMA SYSCAT TO ROLE TOKEN_ADMIN;
--GRANT EXECUTE ON FUNCTION SYSPROC.AUTH_LIST_AUTHORITIES_FOR_AUTHID TO ROLE TOKEN_ADMIN;

-- SERVICE_ADMIN - Min privileges to create, execute and describe services
--               - Also allows GRANT and REVOKE permissions to service users
--               - Allows token creation for this user
--               - Allows all tables in the GOSALES schema to be selected.
--               - Assumes REST_SERVICES schema already created
-- db2 revoke connect on database from role service_admin
GRANT CONNECT ON DATABASE TO ROLE SERVICE_ADMIN;
GRANT SELECTIN ON SCHEMA SYSCAT TO ROLE SERVICE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON DB2REST.RESTSERVICE TO ROLE SERVICE_ADMIN;
GRANT ALL ON SCHEMA REST_SERVICES TO ROLE SERVICE_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE SYSPROC.ADMIN_CMD TO ROLE SERVICE_ADMIN;
GRANT EXECUTE ON FUNCTION SYSPROC.AUTH_LIST_AUTHORITIES_FOR_AUTHID TO ROLE SERVICE_ADMIN;
-- Grant authorities on tables used in any service created by this user id
GRANT SELECTIN ON SCHEMA gosales TO ROLE SERVICE_ADMIN;
GRANT INSERTIN, UPDATEIN, DELETEIN ON SCHEMA gosales TO ROLE SERVICE_ADMIN;



-- SERVICE_USER - Min privileges to execute services in the REST_SERVICES schema
--              - and describe any service
--               - Allows token creation for this user
--REVOKE CONNECT ON DATABASE FROM ROLE SERVICE_USER
GRANT CONNECT ON DATABASE TO ROLE SERVICE_USER;
GRANT EXECUTE ON PROCEDURE SYSPROC.ADMIN_CMD TO ROLE SERVICE_USER;
--GRANT EXECUTEIN ON SCHEMA REST_SERVICES TO ROLE SERVICE_USER;
GRANT EXECUTE ON FUNCTION SYSPROC.AUTH_LIST_AUTHORITIES_FOR_AUTHID TO ROLE SERVICE_USER;

